### PR TITLE
Allow preparedStatementThreshold to be 0 to disable the cache.

### PR DESCRIPTION
**Pull request by aoganezo**
## Purpose
Close https://github.com/ballerina-platform/ballerina-library/issues/7345 by allowing the disablement of the prepare statement threshold.
## Checklist
- [X] Linked to an issue
- [X] Updated the changelog
- [x] Added tests
- [X] Updated the spec
- [ ] Checked native-image compatibility

### CODE REVIEW

**Review by daneshk — APPROVED** [review]
LGTM

**Comment by daneshk** [comment]
@aoganezo We also need to change the compiler validation of those configurations at https://github.com/ballerina-platform/module-ballerinax-postgresql/blob/main/compiler-plugin/src/main/java/io/ballerina/stdlib/postgresql/compiler/Utils.java#L160
Could you please check it

**Comment by daneshk** [comment]
@aoganezo, I would like to explain the request a bit more. In the connector, we have both compiler-level validation and runtime-level validation. Your fix contains the runtime-level change, but the compiler still doesn't allow disabling the caching. I will merge your PR and make the compiler-level change and release.

**Comment by aoganezo** [comment]
> @aoganezo, I would like to explain the request a bit more. In the connector, we have both compiler-level validation and runtime-level validation. Your fix contains the runtime-level change, but the compiler still doesn't allow disabling the caching. I will merge your PR and make the compiler-level change and release. Thank you

Thanks for the context @daneshk , and for getting to it before me. Much appreciated!

**Pull request merged**
